/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class KoinoniaIcons {
  KoinoniaIcons._();

  static const _kFontFam = 'KoinoniaIcons';
  static const String? _kFontPkg = null;

  static const IconData spray_can =
      IconData(0xf5bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pray =
      IconData(0xf683, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData praying_hands =
      IconData(0xf684, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
